import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PackalinkConfig } from '../define-config.js';
import { $ } from '../utils/$.js';
import { getPackageJson } from '../utils/get-package-json.js';
import { log } from '../utils/log.js';

import { processAdditionalDeps } from './process-additional-deps.js';
import { processDedupePeers } from './process-dedupe-peers.js';
import { processLink, type ProceedPackalinkLink } from './process-link.js';

export const run = (config: PackalinkConfig) => {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);

  const linkerDir = path.resolve(__dirname, '../');
  const projectDir = config.sourceDirForLinking ?? process.cwd();

  const linkerPackageJson = getPackageJson({
    packageDescription: `packalink`,
    pathWhereContainsPackageJson: linkerDir,
    ignoreFilesCheck: true,
  });

  const linkerVersion = linkerPackageJson.version ?? 'unknown';

  log(`[packalink]`, { isGroupStart: true });
  log('версия:', { data: linkerVersion });
  log('директория:', { data: linkerDir });
  log(`[packalink]`, { isGroupEnd: true });

  log('Рабочая директория:', { data: projectDir });

  /**
   * @example /home/username/projects/js2me-kit
   */
  const targetDirForLinking =
    config.targetDirForLinking && path.resolve(config.targetDirForLinking);

  if (targetDirForLinking && !existsSync(targetDirForLinking)) {
    throw log(
      `Не удалось найти директорию для линковки ${config.targetDirForLinking}`,
      {
        type: 'error',
      },
    );
  }

  if (config.links.length === 0) {
    log('Список линков не найден', { type: 'warn' });
    return;
  }

  const viteCacheDir = path.resolve(projectDir, './node_modules/.vite');

  if (existsSync(viteCacheDir)) {
    log('Очищаем кэш Vite', { level: 1 });

    $(`rm -rf ${viteCacheDir}`, {
      safe: true,
      onSucceed: () => {
        log('Успешно', {
          nested: true,
          type: 'success',
        });
      },
      onFailed: (e) => {
        log('Неудача', {
          nested: true,
          type: 'error',
          data: e,
        });
      },
    });
  }

  const proceedLinks = config.links.map((link) => {
    const linkDetails =
      typeof link === 'string'
        ? {
            packageName: link,
          }
        : link;

    return processLink(projectDir, config, linkDetails);
  });

  proceedLinks.forEach((proceedLink) => {
    processAdditionalDeps(projectDir, config, proceedLink, proceedLinks);
    processDedupePeers(proceedLink, proceedLinks);
  });

  // --- Generate Vite resolve.dedupe plugin ---
  // Symlinks in dist/node_modules/ fix Node.js and production builds (Rollup),
  // but Vite's dev server uses its own module graph for @fs files and doesn't
  // follow those symlinks for module identity. The only reliable fix is
  // resolve.dedupe. We generate a small Vite plugin that the user adds to
  // their vite.config.ts.
  const dedupePackages = collectDedupePackages(proceedLinks);
  if (dedupePackages.length > 0) {
    generateViteDedupePlugin(projectDir, dedupePackages);
  }
};

/**
 * Collect all package names that should go into resolve.dedupe:
 * - All linked packages themselves
 * - All their peer dependencies (already deduped via symlinks, but Vite needs this too)
 */
const collectDedupePackages = (
  links: ProceedPackalinkLink[],
): string[] => {
  const seen = new Set<string>();
  const result: string[] = [];

  const add = (name: string) => {
    if (!seen.has(name)) {
      seen.add(name);
      result.push(name);
    }
  };

  for (const link of links) {
    // The linked package itself must be deduped
    add(link.packageName);

    // Its peer deps too (Vite can duplicate them via @fs as well)
    try {
      const packageJson = getPackageJson({
        packageDescription: link.packageName,
        pathWhereContainsPackageJson: link.targetDirForLinking,
        ignoreFilesCheck: true,
      });
      for (const dep of Object.keys(packageJson.peerDependencies ?? {})) {
        add(dep);
      }
      // Also include direct deps that are themselves linked
      const linkedNames = new Set(links.map((l) => l.packageName));
      for (const dep of Object.keys(packageJson.dependencies ?? {})) {
        if (linkedNames.has(dep)) {
          add(dep);
        }
      }
    } catch {
      // package.json not found — skip
    }
  }

  return result;
};

/**
 * Write `packalink-dedupe.ts` — a Vite plugin the user imports and adds
 * to their vite.config.ts plugins array.
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import { packalinkDedupe } from './packalink-dedupe'
 * export default defineConfig({ plugins: [packalinkDedupe()] })
 * ```
 */
const generateViteDedupePlugin = (
  projectDir: string,
  packages: string[],
): void => {
  const filePath = path.resolve(projectDir, 'packalink-dedupe.ts');
  const content = `// Generated by packalink — do not edit.
// Add to vite.config.ts: import { packalinkDedupe } from './packalink-dedupe'
// Then: plugins: [packalinkDedupe()]
import type { Plugin } from 'vite';
export const packalinkDedupe = (): Plugin => ({
  name: 'packalink-dedupe',
  config: () => ({
    resolve: {
      dedupe: ${JSON.stringify(packages, null, 4)},
    },
  }),
});
`;

  writeFileSync(filePath, content, 'utf8');

  log(`Vite dedupe plugin → ${filePath}`, { type: 'info', level: 1 });
  log(
    `Добавь в vite.config.ts:\n` +
      `  import { packalinkDedupe } from './packalink-dedupe'\n` +
      `  plugins: [packalinkDedupe()]`,
    { type: 'info', level: 1 },
  );
};
